-- 0003_add_idea_and_seed_topics.sql

-- Add idea_description to teams table if not exists
ALTER TABLE public.teams ADD COLUMN IF NOT EXISTS idea_description TEXT;

-- Clear previous dummy topics if any exist so we can seed fresh
DELETE FROM public.problem_statements;

-- Seed the 10 real problem statements
INSERT INTO public.problem_statements (id, domain, title, description) VALUES 
(1, 'Urban Mobility', 'Enhancing Urban Commuting Efficiency and Non-Motorized Road User Safety', 'Rapid urbanization has intensified challenges in city transport systems, leading to severe bottlenecks in everyday mobility and rising safety concerns for non-motorized road users. Commuters in dense urban centers face major inefficiencies during daily travel. The lack of integrated, real-time mobility guidance prevents drivers from choosing optimal routes. Concurrently, pedestrians and cyclists continue to experience high risks of conflict with vehicular traffic. Traditional static infrastructure fails to provide timely warnings.'),
(2, 'Smart Commerce', 'Empowering Small Retailers Through Digital Visibility and Automated Store Operations', 'Small and independent brick-and-mortar businesses face significant operational and competitive hurdles. Nearby shoppers frequently lack real-time visibility into local product availability, leading them to rely on distant e-commerce platforms. Inside the physical store, manual checkout processes slow down transaction times, lead to long wait times, and expose retailers to inventory discrepancies and unrecorded shrinkage due to limited oversight.'),
(3, 'Climate & Natural Resources', 'Optimizing Local Resource Management through Continuous Monitoring and Behavioral Insights', 'Residential spaces, educational campuses, and small enterprises lack real-time visibility into their daily resource consumption across water, energy, and waste streams. Unnoticed infrastructure failures, particularly hidden water leaks, cause severe cumulative resource loss. Traditional static monitoring methods fail to identify abnormal flow rates or notify stakeholders dynamically.'),
(4, 'Connected Communities', 'Accelerating Emergency Response and Enhancing Safety Accessibility Across Communities', 'During critical safety incidents, residents face severe friction in initiating timely calls for help. Traditional reporting channels are fragmented, causing delays. The issue is exacerbated for vulnerable demographics who may find navigating complex smartphone applications difficult during high-stress scenarios. Relying exclusively on app-based reporting excludes these groups from rapid assistance.'),
(5, 'Travel & Exploration', 'Enhancing Personalized Cultural Exploration and Belonging Security for Travelers', 'Travelers visiting unfamiliar cities frequently struggle to curate cohesive itineraries. Mainstream travel routes often overshadow lesser-known cultural sites, leaving visitors with generic travel experiences. At the same time, journey security remains a primary concern. Mishandled luggage and fear of property loss introduce significant stress. Relying on passive transit tracking leaves travelers vulnerable.'),
(6, 'Entertainment & Creative World', 'Streamlining Creator Workflows and Elevating In-Person Audience Engagement', 'Independent content creators are often overwhelmed by technical, administrative, and post-production tasks, diverting critical time away from original artistic creation. Concurrently, live entertainment venues struggle to deliver dynamic, highly interactive experiences. Traditional event setups rely on static environmental effects that fail to adapt responsively to real-time crowd energy.'),
(7, 'Bioinformatics', 'Accelerating Multi-Omics Data Integration and Predictive Biomarker Discovery for Precision Medicine', 'Modern biomedical research generates massive volumes of heterogeneous multi-omics data. Researchers struggle to effectively integrate these high-dimensional datasets to uncover meaningful biological insights due to high computational overhead. Identifying reliable disease-specific diagnostic biomarkers remains a slow, error-prone manual process.'),
(8, 'Biotechnology', 'Optimizing Bioprocess Control and Real-Time Metabolic Monitoring for Sustainable Bio-Production', 'Industrial and laboratory-scale biomanufacturing processes frequently suffer from suboptimal yield efficiency and batch-to-batch variability. Bio-engineers lack intuitive, centralized systems for continuous, real-time monitoring of critical process parameters. Without dynamic feedback control loops, unexpected metabolic shifts can lead to complete batch failures.'),
(9, 'Cybersecurity', 'Mitigating Advanced Digital Threats and Securing Distributed Infrastructure', 'As organizations and critical public utilities become increasingly interconnected, the attack surface for sophisticated cyber threats expands. Enterprises struggle to maintain real-time visibility and defensive posture against advanced persistent threats. Traditional reactive security frameworks often fail to detect novel attack patterns or respond swiftly enough to mitigate zero-day exploits.'),
(10, 'Open Innovation & Cross-Departmental Solutions', 'Harnessing Cross-Disciplinary Synergies for Multi-Departmental Problem-Solving', 'Complex societal and industrial challenges frequently span multiple operational boundaries. Teams working on cross-functional initiatives face severe friction in sharing domain-specific data and standardizing metrics. The lack of interoperable collaboration tools leads to fragmented problem-solving and redundant efforts when combining hardware, software, economic, and administrative insights.');

-- Reset sequence for id
SELECT setval('public.problem_statements_id_seq', 10);
